spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
application:
  security:
    jwt:
      secret-key: e5354babb1174ae24fdb6ae3cb15ce6e1e3508f49932c92dc356c67230c67210
