spring:
  application:
    name: SyncUpV2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 2592000000 # a month
external:
  api:
    valorant:
      endpoint: https://valorant-api.com/v1/
    imgur:
        endpoint: https://api.imgur.com/3/
