spring:
  # datasource:
  # url: jdbc:postgresql://localhost:5432/syncup
  # username: postgres
  # password: admin
  # driver-class-name: org.postgresql.Driver
application:
  security:
    jwt:
      secret-key: e5354babb1174ae24fdb6ae3cb15ce6e1e3508f49932c92dc356c67230c67210
external:
  api:
    imgur:
      client-id: 863fbdb17bc408a