name: Maven Unit Test
on:
  push:
    branches:
      - master
      - main
      - 'releases/*'
      - 'feature/*'
jobs:
  mvn-clean-test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.8-eclipse-temurin-22
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: mvn-clean-package
        run: |
          mvn clean test